# Generated by Django 5.2.15 on 2026-06-23 07:45

import campaign.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('voucher', 'Gift Voucher'), ('food', 'Food Coupon'), ('drink', 'Free Drink'), ('movie', 'Movie Ticket'), ('concert', 'Concert Ticket'), ('other', 'Other')], max_length=20)),
                ('total_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative odds of being selected on the wheel')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prizes/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Enter a valid mobile number.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('college_name', models.CharField(max_length=200)),
                ('plus_two_completion_year', models.PositiveIntegerField()),
                ('mobile_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('plus2_certificate', '+2 Pass Certificate / Marksheet'), ('other', 'Additional document')], max_length=30)),
                ('file', models.FileField(upload_to=campaign.models.document_upload_path)),
                ('is_required', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaign.participant')),
            ],
        ),
        migrations.CreateModel(
            name='SpinSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_cookie_id', models.CharField(db_index=True, max_length=64)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('status', models.CharField(choices=[('pending_form', 'Waiting for form'), ('completed', 'Form submitted'), ('expired', 'Expired / abandoned')], default='pending_form', max_length=20)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaign.prize')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='spin_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='campaign.spinsession'),
        ),
        migrations.AddIndex(
            model_name='spinsession',
            index=models.Index(fields=['ip_address', 'spun_at'], name='campaign_sp_ip_addr_ed9862_idx'),
        ),
        migrations.AddIndex(
            model_name='spinsession',
            index=models.Index(fields=['device_fingerprint'], name='campaign_sp_device__bc911a_idx'),
        ),
    ]
