# Generated by Django 5.2.15 on 2026-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='is_prize',
            field=models.BooleanField(default=True, help_text="Uncheck for 'better luck next time' segments"),
        ),
    ]
